---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: vayer/0r9an1zz3r_api:1.0.2
          ports:
            - containerPort: 5000
          env:
            - name: APP_NAME
              value: "0r9an1zz3r"
            - name: DB_HOST
              value: "postgres_db"
            - name: DB_DATABASE
              value: "0r9an1zz3r_db"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_PORT
              value: "5432"
            - name: JWT_SECRET
              value: "verystrongpasswordthatisusedforasecret123"
            - name: UPLOAD_FOLDER
              value: "uploads"
            - name: FLASK_APP
              value: "main.py"
            - name: FLASK_ENV
              value: "development"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
  type: LoadBalancer
