---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: vayer/0r9an1zz3r_api:1.0.2
          ports:
            - containerPort: 5000
          env:
            - name: APP_NAME
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: APP_NAME
                    optional: false
            - name: DB_HOST
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: DB_HOST
                    optional: false
            - name: DB_DATABASE
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: DB_DATABASE
                    optional: false
            - name: DB_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: DB_USERNAME
                    optional: false
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: DB_PASSWORD
                    optional: false
            - name: DB_PORT
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: DB_PORT
                    optional: false
            - name: JWT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: JWT_SECRET
                    optional: false
            - name: UPLOAD_FOLDER
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: UPLOAD_FOLDER
                    optional: false
            - name: FLASK_APP
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: FLASK_APP
                    optional: false
            - name: FLASK_ENV
              valueFrom:
                  secretKeyRef:
                    name: api-secrets
                    key: FLASK_ENV
                    optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
  type: LoadBalancer
